version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@s2eazr8t9kfhqm3e_tp?TNS_ADMIN=/app/oracle_wallet/
      - SPRING_DATASOURCE_USERNAME=JAVA_BD2
      - SPRING_DATASOURCE_PASSWORD=ClaseFullStack1-
    restart: always